export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/sbin:$PATH"
clear
echo "Workbench release 2.4.4 $(freepages=$(vm_stat | grep free | awk '{print $3}') && free=$(echo "${freepages%?}") && freekb=$(expr $free \* 4096) &&  echo $freekb)k free mem $(uptime | awk '{ print $11 }') cpu `date '+%H:%M:%S %d/%m/%y'`                "
echo "Copyright (C)1987 Commodore-Amiga, Inc."
echo "All rights reserverd."
echo "Release 1.3"
echo "A500/A2000 F Workbench disk.  Release 1.3 version 34.69"
echo 
echo "            ....................       "
echo "         .dssssd///////oyyodsss/       "
echo "         .hooood:::::::oyyohooooy      "
echo "         .hooood+++++++oyyshooooh.     "
echo "         .hoooooooooooooooooooooh.    "
echo "        .:hoss+osssssssssssssssoh.    "
echo "       :-.hohh-.o/        .   doh.    "
echo "      -:..hy/  -:-.-.......-  doh.    "
echo "     / .//.   --   -:.--.::   doh.    "
echo "    / .-     /  +::://-////:  doh.    "
echo "    /        -/:+:+o/o+/o:/:::hoy     "
echo "    /         o//+s. /  ++.-/ -o.     "
echo "    :.        +-/y-:/   o  -+.-+.     "
echo "    .:     -::.   o.                  "
echo "    .:     +    -:                    "
echo "    ./-----/---/                      "
